{% set name = "django-coverage-plugin" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_coverage_plugin-{{ version }}.tar.gz
  sha256: c063d8d49ba2da30fe95d91cf3f0f9f659b55c3f80d4a029d619b2b3144b1206

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - coverage

test:
  imports:
    - django_coverage_plugin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nedbat/django_coverage_plugin
  summary: Django template coverage.py plugin
  license: Apache-2.0
  license_file:
    - NOTICE.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
