{% set name = "deltalake" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deltalake-{{ version }}.tar.gz
  sha256: b8793a1c7a1219c8935ed9926a6870c9341597396c0f50bf6ff98c323d06ee0f

build:
  noarch: python
  script: |
    rustup toolchain install ${RUST_TOOLCHAIN} && rustup default ${RUST_TOOLCHAIN}
    rustup target add wasm32-unknown-emscripten --toolchain ${RUST_TOOLCHAIN}  
   {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - python >=3.8,<3.9
    - maturin >=0.14,<0.15
    - pip
  run:
    - python >=3.8,<3.9
    - pyarrow >=7
    - typing-extensions
  run_constrained:
    - pandas <2.0
    - pyspark
    - delta-spark
    - numpy ==1.22.2

test:
  imports:
    - deltalake
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/delta-io/delta-rs
  summary: Native Delta Lake Python binding based on delta-rs with Pandas integration
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
